### ISSUE TITLE
Customize syntax for inline media queries

### ISSUE THREAD

**Issue by ghost** [ConciseCSS/preprocessor#23]
Instead of `?if media (…)` use `| media (…)` so it looks like:

```css
:root {
  font-size: --font-size;
  font-size: --font-size-large | media (--small);
}
```

or perhaps consider just:

```css
:root {
  font-size: --font-size;
  font-size: --font-size-large @media (--small);
}
```
